### ISSUE TITLE
The time zone gets lost when writing and reading non UTC DateTime

### ISSUE THREAD

**Issue by hlaueriksson** [paiden/Nett#39]
Example code:

```
using System;
using System.Diagnostics.CodeAnalysis;
using FluentAssertions;
using Xunit;

namespace Nett.Tests
{
    [ExcludeFromCodeCoverage]
    public class FailingTests
    {
        private class Foo
        {
            public DateTime Timestamp { get; set; }
        }

        [Fact]
        public void WriteAndReadDateTime()
        {
            // Arrange
            var subject = new Foo { Timestamp = DateTime.Now };
            var expected = Toml.WriteString(subject);

            // Act
            var result = Toml.WriteString(Toml.ReadString<Foo>(expected));

            // Assert
            result.Should().Be(expected);
        }
    }
}
```

Output:

```
Xunit.Sdk.XunitException
Expected string to be 
"Timestamp = 2018-01-01T22:25:32.010354+01:00\r\n", but 
"Timestamp = 2018-01-01T21:25:32.010354+00:00\r\n" differs near "1:2" (index 24).
   at FluentAssertions.Execution.XUnit2TestFramework.Throw(String message) in C:\projects\fluentassertions-vf06b\Src\FluentAssertions.Net45\Execution\XUnit2TestFramework.cs:line 35
   at FluentAssertions.Execution.AssertionScope.FailWith(String message, Object[] args) in C:\projects\fluentassertions-vf06b\Src\Core\Execution\AssertionScope.cs:line 197
   at FluentAssertions.Primitives.StringEqualityValidator.ValidateAgainstMismatch() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringEqualityValidator.cs:line 48
   at FluentAssertions.Primitives.StringValidator.Validate() in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringValidator.cs:line 48
   at FluentAssertions.Primitives.StringAssertions.Be(String expected, String because, Object[] becauseArgs) in C:\projects\fluentassertions-vf06b\Src\Core\Primitives\StringAssertions.cs:line 41
   at Nett.Tests.FailingTests.WriteAndReadDateTime() in C:\work\github\Nett\Test\Nett.Tests\FailingTests.cs:line 27
```

**Comment by paiden** [comment]
The problem here is, that at some point in the background the following happens:

```
var dateTimeOffset = TomlParser.ParseTomlValue(...);
foo.TimeStamp = dateTimeOffset.UtcDateTime;
```

To fix your use case this needs to be changed to:

```
var dateTimeOffset = TomlParser.ParseTomlValue(...);
foo.TimeStamp = dateTimeOffset.LocalDateTime;
```

But that would simply cause the following test case to fail:
```
       [Fact]
        public void WriteAndReadDateTime()
        {
            // Arrange
            var subject = new Foo { Timestamp = DateTime.UtcNow };
            var expected = Toml.WriteString(subject);

            // Act
            var result = Toml.WriteString(Toml.ReadString<Foo>(expected));

            // Assert
            result.Should().Be(expected);
        }
```

When converting from a TomlValue<DateTime> to the foo.TimeSpan:DateTime there is no way to tell if Utc or Local time is expected. Or at least I don't see one ATM.

It's debatable, if DateTime.Local would be the better default, as humans are more used to work with local dates instead of UTC. I'll think a little bit more about that. 

If you just need to fix your use case, you can adapt the settings object to:

```
private class Foo
{
       public DateTimeOffset Timestamp { get; set; }
}
```
and your test case will succeed.

**Comment by hlaueriksson** [comment]
Thanks for the explanation! I think UTC it the way to go everywhere in all code bases.
